	#!/usr/bin/env bash

"${mysql[@]}" <<-EOSQL
	use mysql;
	CREATE USER '$DATABASE_USER'@'%' IDENTIFIED BY '$DATABASE_PASSWORD';
	GRANT ALL PRIVILEGES ON *.* TO '$DATABASE_USER'@'%' WITH GRANT OPTION;
	FLUSH PRIVILEGES;
	
	CREATE DATABASE $SAGA_DATABASE_NAME;
EOSQL
