spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: fdc-queryside-agreement-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fdc
axon:
  eventhandling:
    processors:
      AgreementEventProcessor:
        mode: SUBSCRIBING
        source: AgreementMessageSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8787
logging:
  level:
    org.springframework.web: ERROR
    org.springframework.controllers: ERROR
    com.fdc: DEBUG
    org.hibernate: ERROR
management:
  security:
     enabled: false    
security:
  basic:
    enabled: false
fdc:
  integration:
    agreement-read: AGREEMENT_READ
---
spring:
  profiles: cloud
  application:
    name: fdc-queryside-agreement-service
axon:
  eventhandling:
    processors:
      AgreementEventProcessor:
        mode: SUBSCRIBING
        source: AgreementMessageSource
eureka:
  client:
    serviceUrl:
      defaultZone: https://fdc-local-eureka-server.cfapps.io/eureka
logging:
  level:
    org.springframework.web: ERROR
    org.springframework.controllers: ERROR
    com.fdc: DEBUG
    org.hibernate: ERROR
management:
  security:
     enabled: false    
security:
  basic:
    enabled: false
fdc:
  integration:
    agreement-read: AGREEMENT_READ    