spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: fdc-employer-registration
  datasource:
    url: jdbc:mysql://localhost:3306/fdc_employer_registration_saga
    username: root
    password: rana1970
    max-active: 5
    validation-query: select 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 6666
logging:
  level:
    org.springframework.web: ERROR
    org.springframework.controllers: ERROR
    com.fdc: DEBUG
    org.hibernate: ERROR
fdc:
  integration:
    employer-registration-queue: EMPLOYER_REGISTRATION_SAGA
management:
  security:
     enabled: false    
security:
  basic:
    enabled: false
---
spring:
  profiles: container
  application:
    name: fdc-employer-registration
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    max-active: 5
    validation-query: select 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
server:
  port: 6666
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.controllers: DEBUG
    com.fdc: DEBUG
    org.hibernate: DEBUG
fdc:
  integration:
    employer-registration-queue: EMPLOYER_REGISTRATION_SAGA
management:
  security:
     enabled: false    
security:
  basic:
    enabled: false
---
spring:
  profiles: cloud
  application:
    name: fdc-employer-registration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: https://fdc-local-eureka-server.cfapps.io/eureka
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.controllers: DEBUG
    com.fdc: DEBUG
    org.hibernate: DEBUG
fdc:
  integration:
    employer-registration-queue: EMPLOYER_REGISTRATION_SAGA
management:
  security:
     enabled: false    
security:
  basic:
    enabled: false