spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: fdc-queryside-customer-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fdc
axon:
  eventhandling:
    processors:
      CustomerEventProcessor:
        mode: SUBSCRIBING
        source: CustomerMessageSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 4545
logging:
  level:
    org.springframework.web: ERROR
    org.springframework.controllers: ERROR
    com.fdc: DEBUG
    org.hibernate: ERROR
management:
  security:
     enabled: false    
security:
  basic:
    enabled: false
fdc:
  integration:
    customer-read: CUSTOMER_READ

---
spring:
  profiles: cloud
  application:
    name: fdc-queryside-customer-service
axon:
  eventhandling:
    processors:
      CustomerEventProcessor:
        mode: SUBSCRIBING
        source: CustomerMessageSource
eureka:
  client:
    serviceUrl:
      defaultZone: https://fdc-local-eureka-server.cfapps.io/eureka
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.controllers: DEBUG
    com.fdc: DEBUG
    org.hibernate: DEBUG
management:
  security:
     enabled: false    
security:
  basic:
    enabled: false
fdc:
  integration:
    customer-read: CUSTOMER_READ    